"""mudar nome

Revision ID: 7d10324f1da2
Revises: 83c7e819bacd
Create Date: 2023-07-28 10:51:50.481654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d10324f1da2'
down_revision = '83c7e819bacd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agedamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servico', sa.String(length=200), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_agendamento', sa.DateTime(), nullable=False),
    sa.Column('cliente_nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('todo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(length=200), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.Column('date_appointment', sa.DATETIME(), nullable=False),
    sa.Column('client_name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('agedamento')
    # ### end Alembic commands ###
