"""Descrição da alteração

Revision ID: 83c7e819bacd
Revises: 
Create Date: 2023-07-26 14:56:37.939742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c7e819bacd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_appointment', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('client_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('client_name')
        batch_op.drop_column('date_appointment')

    # ### end Alembic commands ###
