"""Descrição da migração

Revision ID: c77872220c6f
Revises: 7d10324f1da2
Create Date: 2023-07-28 11:02:30.706741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77872220c6f'
down_revision = '7d10324f1da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agendamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servico_banco', sa.String(length=200), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_agendamento', sa.DateTime(), nullable=False),
    sa.Column('nome_cliente', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('agedamento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agedamento',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('servico', sa.VARCHAR(length=200), nullable=False),
    sa.Column('data_criacao', sa.DATETIME(), nullable=True),
    sa.Column('data_agendamento', sa.DATETIME(), nullable=False),
    sa.Column('cliente_nome', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('agendamento')
    # ### end Alembic commands ###
